### ISSUE TITLE
Make the namespace customisable

### ISSUE THREAD

**Issue by davidpaulrosser** [kilkelly/redux-localstorage-simple#1]
Hey,

Could you add the option to make the namespace customisable?

Cheers,

**Comment by kilkelly** [comment]
Hi David Paul,
I've just published a minor version update to include a customisable namespace. The documentation has been updated accordingly. Check it out and let me know if it works for you.

**Comment by davidpaulrosser** [comment]
Hey,

This looks perfect. Thanks for adding it 👌🏻
