### ISSUE TITLE
Immutable.js is imported even if not needed (140kb extra bundle size)

### ISSUE THREAD

**Issue by glebtv** [kilkelly/redux-localstorage-simple#10]
Immutable.js is a large library (140+kb) and it is imported, and by default not used.

Please consider adding an alternative dist file to import which doesn't have it.

**Comment by kilkelly** [comment]
Hi @glebtv , I'm going to deprecate support for Immutable.js structures in the next imminent release. I have considered this for a while now since I don't see it used much. Developers will still be able to use the 1.4.0 version if they need the Immutable.js support. Thanks for your feedback.

**Comment by kilkelly** [comment]
Update! Version 2.0.0 has been released.
https://github.com/kilkelly/redux-localstorage-simple/releases/tag/v2.0.0
