### ISSUE TITLE
Dependency object-merge is missing 

### ISSUE THREAD

**Issue by bobtista** [kilkelly/redux-localstorage-simple#101]
Build was failing for me in a separate app because it couldn't resolve object-merge, which was used in this package and isn't included in its package.json
The fix was to run `npm install object-merge    `
I've got a branch but don't have permissions to push my branch and create a PR

**Comment by kilkelly** [comment]
Hi @bobtista , package `object-merge` was swapped out for package `merge` in the most recent version. Have you the most recent version installed (2.4.0)?

**Comment by bobtista** [comment]
You're right - I think I just needed to update locally. Thank you for the
quick reply!

**Comment by kilkelly** [comment]
No worries! Glad it worked for you.
