### ISSUE TITLE
Vulnerability in dependency `merge` requires an update

### ISSUE THREAD

**Issue by JNotelddim** [kilkelly/redux-localstorage-simple#102]
See advisory,
https://www.npmjs.com/advisories/1666

Dependency `merge` needs a bump to `2.1.1.`

**Comment by JNotelddim** [comment]
https://github.com/kilkelly/redux-localstorage-simple/pull/74

**Comment by JNotelddim** [comment]
For anyone else having issues, here's a forked version you can use for now:

https://www.npmjs.com/package/redux-localstorage-simple-metalab

**Comment by kilkelly** [comment]
Hi @JNotelddim , sorry for the delay. The update to `merge` has now been made https://github.com/kilkelly/redux-localstorage-simple/commit/e8169ba82435f0a12e21cf5cecf627e3af5a3038
Thank you 💯

**Comment by JNotelddim** [comment]
Thank you kindly! 🙏
