### ISSUE TITLE
clear and combineLoads missing from typescript

### ISSUE THREAD

**Issue by ridem** [kilkelly/redux-localstorage-simple#14]
I just noticed they were missing from the typescript definition exports.
You probably want to add them.

Great lib!

**Comment by kilkelly** [comment]
Hi @ridem , I've just made this change. I'd be grateful if you could have a look and see if everything looks ok?
https://github.com/kilkelly/redux-localstorage-simple/blob/master/dist/index.d.ts
Thanks for the report.

**Comment by ridem** [comment]
All good! 👍
