### ISSUE TITLE
'save' middleware doesn't return the result value

### ISSUE THREAD

**Issue by jrpedrianes** [kilkelly/redux-localstorage-simple#16]
Checking the code of save middleware the result of a invocation to 'next' method is losted (see: https://github.com/kilkelly/redux-localstorage-simple/blob/master/src/index.js#L161) is this done by desing?.

Checking the redux documentation seems that the middlewares have to return the result of next method invocation: https://redux.js.org/api-reference/applymiddleware

**Comment by kilkelly** [comment]
Good catch! I have just added https://github.com/kilkelly/redux-localstorage-simple/commit/98c03c5acd417fb3640c8cf553036b70c4d42628 to fix this. No it wasn't by design, simply an overlook on my part. Thanks @jrpedrianes 👍
