### ISSUE TITLE
Need an example of Clear()

### ISSUE THREAD

**Issue by bhupesh-sf** [kilkelly/redux-localstorage-simple#17]
Whenever a user hit logout I need to clear the localStorage but I am not getting how to use clear function of it.

Any help is appreciated.

**Comment by kilkelly** [comment]
If you aren't working within a specific namespace using the clear function is as simple as calling:

```clear()```

You can call this somewhere within your logout function and it will clear all LocalStorage entries associated with this library.

For an example of using the clear function with a namespace please refer to the README.
