### ISSUE TITLE
combineLoads signature causes TypeScript error

### ISSUE THREAD

**Issue by dbartholomae** [kilkelly/redux-localstorage-simple#20]
When trying to use the package I get the following error message:
[at-loader] ./node_modules/redux-localstorage-simple/dist/index.d.ts:23:40 
    TS1047: A rest parameter cannot be optional.

This seems to relate to
```
export function combineLoads(...loads?: object[]): object
```
and as far as I can fathom the error message is correct and it should be 
```
export function combineLoads(...loads: object[]): object
```

I could set up a PR if interested.

**Comment by dbartholomae** [comment]
Just saw this was already fixed by #18. When will this be released to npm?

**Comment by kilkelly** [comment]
Hi @dbartholomae , apologies. That was an oversight on my part. Just published to npm and added a new release https://github.com/kilkelly/redux-localstorage-simple/releases/tag/v2.1.4
Thanks 👍

**Comment by dbartholomae** [comment]
Thanks! No need to apologize, I appreciate everyone who takes their free time to support the community with Open Source :)
