### ISSUE TITLE
TypeScript compile error

### ISSUE THREAD

**Issue by romor** [kilkelly/redux-localstorage-simple#21]
The following code
<pre>
import { createStore, applyMiddleware } from "redux";
import { save, load } from "redux-localstorage-simple";
const createStoreWithMiddleware = applyMiddleware(
        save()
    )(createStore);
</pre>

raises the following error:
<pre>
ERROR in [at-loader] ./src/index.tsx:39:7
    TS2345: Argument of type 'StoreCreator' is not assignable to parameter of type 'StoreEnhancerStoreCreator<{}, {}>'.
  Types of parameters 'enhancer' and 'preloadedState' are incompatible.
    Type 'DeepPartial<any> | undefined' is not assignable to type 'StoreEnhancer<any, any> | undefined'.
      Type 'DeepPartial<any>' is not assignable to type 'StoreEnhancer<any, any>'.
        Type 'DeepPartial<any>' provides no match for the signature '(next: StoreEnhancerStoreCreator<{}, {}>): StoreEnhancerStoreCreator<any, any>'`
</pre>

How can I resolve this?

**Comment by kilkelly** [comment]
This looks like an issue with the Redux library. Try this link https://github.com/palantir/redoodle/issues/4

**Comment by romor** [comment]
I did not manage to resolve it by applying proper type definition, but just by removing type checking here:
<pre>
const createStoreWithMiddleware = applyMiddleware(
    save(),
)(createStore as any);
</pre>

**Comment by kilkelly** [comment]
Glad you got it fixed @romor
