### ISSUE TITLE
Add option to ignore state branches.

### ISSUE THREAD

**Issue by dotintegral** [kilkelly/redux-localstorage-simple#35]
Apart from having `states` argument for `save()` method, It would be really useful to have an option to specify certain branches that should be ignored.

For example, I'm using `connected-react-router` in my application and when combined with `redux-localstorage-simple`, it's impossible to navigate properly when accessing different pages directly via URL. Currently I have to specify every state branch that I want to persist, which is every branch other than `router`. This becomes a bit annoying when working with big state trees. It would be awesome if I could simply state, that I want to ignore only `router`.

Example:
A state:
```
{
  router: ...,
  user: ...,
  form: ...,
  data: ...,
  otherData: ...,
 /* and many more */
}
```

How I need to use the `save()` method currently:
```
applyMiddleware(save({
  states: ['user', 'form', 'data', 'otherData', /* and many more */ ]
}))
```

How my proposed feature would work:
```
applyMiddleware(save({
  ignore: ['router']
}))
```

**Comment by kilkelly** [comment]
Hi @dotintegral, sorry for the very late reply!

May I suggest the following solution?

```
function ignoreStates(statesToIgnore, state) {
  return Object.keys(yourState).filter(function(key) {
    if (statesToIgnore.indexOf(key) === -1) {
      return key
    }
  })
}

applyMiddleware(save({
  states: ignoreStates(['router', 'otherStateToIgnore', 'yetAnotherStateToIgnore'], yourState)
}))
```

...where `yourState` is your reducer or combined reducers.

**Comment by dotintegral** [comment]
@kilkelly Thanks for getting back.

As you wrote, I did something similar in my app. I just thought it would be pretty useful, if there would be such possibility out of the box.

It's never a big problem to write custom wrapper that does the additional logic, but it's always nice if the logic I'm looking for is already implemented and just can use it 😉

**Comment by kilkelly** [comment]
Hi again @dotintegral . v2.2.0 released with `ignoreStates` option added. Let me know if it works for you 👍 
https://github.com/kilkelly/redux-localstorage-simple/releases/tag/v2.2.0

**Comment by dotintegral** [comment]
Looks great! Thank you! 👍
