### ISSUE TITLE
Install on react native redux project failed

### ISSUE THREAD

**Issue by billpatterson** [kilkelly/redux-localstorage-simple#4]
Hi, found this library, tried to incorporate it, didn't work for me (but I appreciate your taking the time to publish it!). I received the error below when trying to run project with this installed.

Setup: react-native project with redux, redux-saga. 

I'm fairly new to this, so it's entirely possible there's some compatibility/extension/something related to ES2015 that I'm assumed to have installed but don't. 

TransformError: <my-project-dir>/node_modules/redux-localstorage-simple/node_modules/immutable/dist/immutable.js: Couldn't find preset "es2015" relative to directory "<my-project-dir>/node_modules/redux-localstorage-simple"

RCTFatal
-[RCTBatchedBridge stopLoadingWithError:]
__25-[RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by kilkelly** [comment]
Hi Bill, I believe this is a Babel related issue. To solve it install babel-preset-es2015...

`npm install --save-dev babel-preset-es2015`

...and add a .babelrc file to the root folder of your project with the following contents

`{ "presets": ["es2015"] }`

I think the immutable.js dependency for redux-localstorage-simple is looking for this es2015 preset. I wasn't aware of this. Thanks for bringing it to my attention and please let me know if this solves the issue for you.
