### ISSUE TITLE
Add namaespace separator option

### ISSUE THREAD

**Issue by acelaya** [kilkelly/redux-localstorage-simple#42]
I have came across this library and it perfectly fits my needs, except for one thing.

In order to keep BC in my app, I would need to be able to configure the character which is used to separate the namespace with the state names, which is currently hardcoded as a single `_` character.

Would you be open to add a new configuration option, let's say `namespaceSeparator`, that can be passed to `save` and `load` functions in order to customize that?

Something in the lines of:

```js
save({
  namespace: 'my_namespace',
  namespaceSeparator: '::'
});

load({
  namespace: 'my_namespace',
  namespaceSeparator: '::'
});
```

If you think this can be useful, I'm open to implement it and provide a PR.

**Comment by acelaya** [comment]
I have created the PR, as I will publish this for my own use: https://github.com/kilkelly/redux-localstorage-simple/pull/43

Feel free to merge it in the main project if you find it useful.

**Comment by kilkelly** [comment]
Thank @acelaya 👍 I'm hoping to get this included very soon, just trying to include another feature added along with the next update (could be later today or tomorrow). Awesome work!

**Comment by acelaya** [comment]
Always happy to help :-)

**Comment by kilkelly** [comment]
Hi again @acelaya. v2.2.0 released 👍 Thanks again!
https://github.com/kilkelly/redux-localstorage-simple/releases/tag/v2.2.0
