### ISSUE TITLE
Is this compatible with redux-toolkit ?

### ISSUE THREAD

**Issue by Flosrn** [kilkelly/redux-localstorage-simple#44]
I tried something like that but it did not work
```
const store = configureStore({
  reducer: rootReducer,
  middleware: [load(), save()],
});
```
docs : 
https://redux-toolkit.js.org/api/configureStore
https://redux-toolkit.js.org/api/getDefaultMiddleware

Any ideas ?

**Comment by inderdhir** [comment]
@Flosrn Try the following:

```
const store = configureStore({
  reducer: rootReducer,
  middleware: [
    ...getDefaultMiddleware(),
    save({
      states: ["playerSlice"], // Make sure you are loading / saving the slice
      namespace: "example",
    }),
  ],
  preloadedState: load({
    states: ["playerSlice"],
    namespace: "example",
  }),
});
```

<img width="211" alt="Screen Shot 2020-05-11 at 10 42 53 PM" src="https://user-images.githubusercontent.com/2235307/81632676-e1478080-93d8-11ea-902c-465399960865.png">

**Comment by Flosrn** [comment]
Thank you @inderdhir, I have already try your solution but I it doesn’t work.  But I think it's because I tried to implement this with Next.js..

**Comment by Uzwername** [comment]
@inderdhir Just 2 things:
1. This is an awesome package, so, big thanks to you & the community behind it.
2. I'm almost sure it makes perfect sense to update Readme.md, so, it includes your wonderful explanation.

I can make a pull for that if no one else is already working on this.
