### ISSUE TITLE
GPL-3 Dependency 

### ISSUE THREAD

**Issue by branislavjenco** [kilkelly/redux-localstorage-simple#58]
Hi, just a note, your `object-merge` dependency has the GPL-3 license. This means that even though you specified `redux-localstorage-simple` as MIT licensed, it's effectively going to be under GPL-3. Might be worth noting it in the readme.

**Comment by TomTomB** [comment]
Because of that I´ve replaced it with a simple spread operation. Works like a charm for me.

Example for [line 412](https://github.com/kilkelly/redux-localstorage-simple/blob/master/src/index.js#L412):
`loadedState = { ...loadedState, ...realiseObject(state, val) };`

**Comment by kilkelly** [comment]
@branislavjenco  Thanks for alerting me to the license on `object-merge`. To fix this I've swapped out for package `merge` which uses the MIT License.

@TomTomB While that would work for states one level deep, it wouldn't work for states with nested levels. So I switched out the package instead.

Thanks all 👍

**Comment by MonsieurMan** [comment]
Seems to me that this issue can be closed :)
