### ISSUE TITLE
Is this compatible with React Native?

### ISSUE THREAD

**Issue by vandervidi** [kilkelly/redux-localstorage-simple#6]
I have  done everything as in the example and i am getting an error : 
**localStorage is not defined**

**Comment by tofikabdullayev** [comment]
Local storage is part of the **HTML5 Web Storage API**, for the mobile apps there are SQL lite and etc.
Take a look to this thread [https://www.reddit.com/r/reactnative/comments/8ugwrz/best_local_storage_option_for_react_native/](https://www.reddit.com/r/reactnative/comments/8ugwrz/best_local_storage_option_for_react_native/)
