### ISSUE TITLE
State for nested store

### ISSUE THREAD

**Issue by Vadorequest** [kilkelly/redux-localstorage-simple#7]
I have a root store called "modules" which contains sub modules, I wonder if I can enable only one sub module and not the whole thing, or if it works only by reducer? Which is quite a limitation in a big app. It was fine at the beginning but now ... :/

**Comment by kilkelly** [comment]
Hi Vadorequest. I use the 'states' configuration option to specify which parts of my root store I want to persist to LocalStorage. In the folder containing my reducers I have an index.js file which allows me to give names to my reducers, which can then be specified in the 'states' configuration option.

I'm away from my workspace at the moment but I can provide a code sample tomorrow if that's useful to you?

**Comment by Vadorequest** [comment]
Hello @kilkelly and thanks for the quick feedback.

Actually, I'm already using those `states` in my app. Here is a sample:

```js
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import { reducer as formReducer } from 'redux-form';
import { reducer as toastrReducer } from 'react-redux-toastr';
import { save, load } from "redux-localstorage-simple"

import simulatorReducer from './simulator/reducer';

const reducers = combineReducers({
  form: formReducer,
  toastr: toastrReducer,
  simulator: simulatorReducer,
});

const syncStatesLocalStorage = ['form'];
const localStorageNamespace = 'simulator';

const defaultInitialState = load({
  states: syncStatesLocalStorage,
  namespace: localStorageNamespace,
});

export default function configureStore(initialState = defaultInitialState) {
  const enhancer = compose(
    applyMiddleware(save({
      states: syncStatesLocalStorage, // Only save those reducers states
      namespace: localStorageNamespace,
      debounce: 900, // Don't save too often, especially when the user is writing text
    })),
    (window.devToolsExtension && process.env.NODE_ENV !== 'production') ? window.devToolsExtension() : f => f,
  );
  return createStore(reducers, initialState, enhancer);
}
```

But now, my app is growing and I need to add more stuff in LocalStorage. My issue is with this line:

`const syncStatesLocalStorage = ['form'];`

I'd like to do something like:

`const syncStatesLocalStorage = ['form', 'simulator.modules.module1'];` with a "nested" path.

So far, I was only using redux-localstorage-simple to store my `form` (redux-form) and it was perfect for my use case. But now I need to add some other values that are deeply nested in my application. And I cannot store `simulator` since it'll store UI steps that I don't wish to store (wouldn't make sense in my use case)

**Comment by kilkelly** [comment]
I see what you mean now. This would be very useful to have as I ran into the exact same issue myself, i.e. not wanting to store UI values. How I solved it at that time was to carefully categorise my reducers into persistable and non-persistable but that is rather an inelegant solution.

I may find some time today to implement your suggestion as I'm currently working on a project where it would be very useful. Stay tuned!

**Comment by Vadorequest** [comment]
Exactly! I had the same thought but then I was like "damn, I have to change my redux store setup because of one lib, what if I add another one and need to switch things other again?", because the easiest way is indeed to separate data and UI, but then things could get messy and I rather like to organize my app by modules, which is easier to maintain.

**Comment by kilkelly** [comment]
Hi again @Vadorequest I have been making progress with this functionality. Currently I can specify to persist a nested piece of reducer state e.g. 'ui.itemsPerPage' to persist the 'itemsPerPage' property while the rest of the 'ui' properties are not persisted. This is useful but I have run into a snag with loading the state back in from LocalStorage. Due to the way redux-localstorage-simple's API is set up, loading back in the 'ui.itemsPerPage' state from LocalStorage will initiate the 'ui' reducer with this state only. This is due to the way createStore works in Redux, you provide it with a 'preloadedState' argument and it sets this as the initial state for your reducer. In my case the 'ui.itemsPerPage' forms the entire initial state for the reducer leaving other properties in the reducer without values.

Here's how my API is looking currently:

```
save({
    states: ["ui.itemsPerPage"]
})
```

```
load({
    states: ["ui.itemsPerPage"]
})
```

Does this make sense?

**Comment by Vadorequest** [comment]
> Due to the way redux-localstorage-simple's API is set up, loading back in the 'ui.itemsPerPage' state from LocalStorage will initiate the 'ui' reducer with this state only.

I'm not quite sure what could be the repercussions without testing it. 

---

This would be my current use case: (see `syncStatesLocalStorage`)

```js
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import { reducer as formReducer } from 'redux-form';
import { reducer as toastrReducer } from 'react-redux-toastr';
import { save, load } from "redux-localstorage-simple"

import simulatorReducer from './simulator/reducer';

const reducers = combineReducers({
  form: formReducer,
  toastr: toastrReducer,
  simulator: simulatorReducer,
});

const syncStatesLocalStorage = ['form']; // XXX Would become ['form', 'simulator.modules.feedback']
const localStorageNamespace = 'simulator';

const defaultInitialState = load({
  states: syncStatesLocalStorage,
  namespace: localStorageNamespace,
});

export default function configureStore(initialState = defaultInitialState) {
  const enhancer = compose(
    applyMiddleware(save({
      states: syncStatesLocalStorage, // Only save those reducers states
      namespace: localStorageNamespace,
      debounce: 900, // Don't save too often, especially when the user is writing text
    })),
    (window.devToolsExtension && process.env.NODE_ENV !== 'production') ? window.devToolsExtension() : f => f,
  );
  return createStore(reducers, initialState, enhancer);
}
```

This is the default state.
```
const initialState = {
  step: 1,
  deviceId: deviceId,
  simulationId: null,
  isModalAdvicesOpen: false,
  settings: resolveSettings(window.SIMULATOR_SETTINGS), // Merge default settings with runtime settings
  modules: {
    feedback: { // TODO LS
      feedbackId: null,
      rating: 0,
      hasSentDescription: false,
      description: '',
    }
  },
};
```

---

I believe it would work fine in my use case, and actually in most use cases. Since we store the whole `simulator.modules.feedback` object, the attributes should match between the default state and the state from the LocalStorage. The only issue that may show up is if some attributes are deleted, which would delete them from LS also, and not load them when reloading the page. But I assume that if some attributes are deleted, then the application is supposed to work without them. I guess that's to the developers to know what they're doing, and potentially have some kind of deepmerge within the reducer to merge the `initialState` with the values retrieved from LS.

=> The current specs look fine and make sense to me!
If you want, I can use your particular branch and see how it behave before you merge it in `master`?

**Comment by kilkelly** [comment]
> Since we store the whole simulator.modules.feedback object, the attributes should match between the default state and the state from the LocalStorage. 

The problem is that while the whole `simulator.modules.feedback` object would be stored in LocalStorage, the properties on the same depth as the `modules` property, namely `step`, `deviceId`, `simulationId`, `isModalAdvicesOpen` and `settings`, are not stored. When loading from LocalStorage the only data loaded is:

```
{
  modules: {
    feedback: { // TODO LS
      feedbackId: null,
      rating: 0,
      hasSentDescription: false,
      description: '',
    }
  }
}
```

So when reload your app's page your code would not find the properties in the initial state passed to your reducer and would crash.

I want to find a solution to this but if it involves too much thought for the developer to get working I may decide not to add it. That would negate the 'simple' part of the library's name :D

I have added the  `states-granular ` branch which contains my work from yesterday and today. You are free to have a look!

**Comment by Vadorequest** [comment]
Alternatively, you could allow an extra parameter `initialState` that does take care of this for the developer. Basically, when doing nesting, this `initialState` would be used as default value, and deep merged with the actual LocalStorage, which would make the app state consistent.

I'll take a look around!

**Comment by kilkelly** [comment]
I like this idea. While this is getting into advanced territory I don't think it would be any harm to add it. Most users seem happy with the simple save(), load() option anyway. 

Let me see what I can do. Nice input, thank you!

**Comment by Vadorequest** [comment]
Yup, I think that's the best way to go, it allows to keep things simple for those who don't use nested stuff, and allow for more granular control when needed.

Most important thing is, it's backward compatible, doesn't do any breaking change, etc.
As long as the doc is explicit about that new feature, it should be pretty simple to use.

**Comment by kilkelly** [comment]
I just did a rough addition and it seemed to work nicely :) I will clean up the code a bit and push it to the branch a little later (may be tomorrow).

**Comment by kilkelly** [comment]
Back again @Vadorequest . I have uploaded my latest work to the `states-granular` branch. It is undocumented for now but I can share how to work with nested data here:

I ran with your `initialState` idea but to be inline with [official Redux documentation](https://redux.js.org/api-reference/createstore) I have renamed it to `preloadedState`. Basically what you have to do it something like this (based off your code above):

```
load({
  states: ['simulator.modules.feedback'],
  preloadedState: <YOUR_INITIALSTATE_HERE>
});
```

This solves the issue of having no data in your reducer's upon app reload, as `preloadedState` now acts as a backup data source.

How to build your `preloadedState` object is entirely up to you. Personally I added my reducer's initial state as an exportable object and referenced in the script containing my redux-localstorage-simple setup.

I recommend uninstalling your currently installed version of `redux-localstorage-simple` and install it again from the `states-granular` branch to get access to the new functionality:

**`npm install git://github.com/kilkelly/redux-localstorage-simple.git#states-granular --save`**

Looking forward to hearing your feedback! Let me know if you need assistance.

**Comment by Vadorequest** [comment]
@kilkelly Awesome. I did exactly the same as I initially intended and it works just great, good job!

Here are the changes I've made for anyone interested:

`store/simulator/reducer.js`
```js
export const initialState = { // NEW "export" here
  step: 1,
  deviceId: deviceId,
  simulationId: null,
  isModalAdvicesOpen: false,
  settings: resolveSettings(window.SIMULATOR_SETTINGS), // Merge default settings with runtime settings
  modules: {
    feedback: {
      feedbackId: null,
      rating: 0,
      hasSentDescription: false,
      description: '',
    }
  },
};
```
---

`store/configureStore.js`

```

import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import { reducer as formReducer } from 'redux-form';
import { reducer as toastrReducer } from 'react-redux-toastr';
import { save, load } from "redux-localstorage-simple"

import simulatorReducer, { initialState as simulatorInitialState} from './simulator/reducer'; // NEW import the initial simulator state

const reducers = combineReducers({
  form: formReducer,
  toastr: toastrReducer,
  simulator: simulatorReducer,
});

const syncStatesLocalStorage = ['form', 'simulator.modules.feedback']; // NEW add the feedback module
const localStorageNamespace = 'simulator';

const defaultInitialState = load({
  states: syncStatesLocalStorage,
  preloadedState: { // NEW add the initial state for my "simulator" sub store
    simulator: simulatorInitialState,
  },
  namespace: localStorageNamespace,
});

export default function configureStore(initialState = defaultInitialState) {
  const enhancer = compose(
    applyMiddleware(save({
      states: syncStatesLocalStorage, // Only save those reducers states
      namespace: localStorageNamespace,
      debounce: 900, // Don't save too often, especially when the user is writing text
    })),
    (window.devToolsExtension && process.env.NODE_ENV !== 'production') ? window.devToolsExtension() : f => f,
  );
  return createStore(reducers, initialState, enhancer);
}
```

Simple, backward compatible and doesn't make it harder to use `redux-localstorage-simple` => I love it :) 💯
