### ISSUE TITLE
?

### ISSUE THREAD

**Issue by bjornoj** [kilkelly/redux-localstorage-simple#8]
I installed with npm install redux-localstorage-simple, and well.. In it was a BitcoinMiner..

**Comment by kilkelly** [comment]
Umm... no. Please have a look at the code. It's all there to see.

**Comment by bjornoj** [comment]
I'm sorry. I should have thought more about my post before opening an issue.
However, when I ran npm install redux-localstorage-simple, installation of a BitcoinMiner was attempted, but not from redux-localstorage-simple files.

**Comment by bjornoj** [comment]
I don't know where to open this issue, but there is a BitcoinMiner lurking somewhere, it was found in libswiftDispatch.dylib.

**Comment by Vadorequest** [comment]
@bjornoj Please list your packages

Also, see this: https://iamakulov.com/notes/npm-malicious-packages/

**Comment by Vadorequest** [comment]
@bjornoj how did you detect the Bitcoin miner? Under what OS?

**Comment by kilkelly** [comment]
> I'm sorry. I should have thought more about my post before opening an issue.

No worries at all. I curious how you detected a miner also. MalwareBytes?
